version: '3'

services:
  # abstract image with twisted package and /src folder
  base:
    image: redis-implemetation-base
    build:
      context: .
      dockerfile: Dockerfile

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    command: ['python3', 'server.py', '--save', '/data']
    stop_signal: SIGINT
    ports:
    - 6379:6379
    volumes:
    - data:/data

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    network_mode: host
    stdin_open: true
    tty: true
  tests:
    build:
      context: .
      dockerfile: ./tests/Dockerfile

volumes:
  data: